version: 0.2

env:
  variables:
    S3_TEMPLATE: "taurus-s3-deploy-template"
    S3_ARTIFACT: "taurus-s3-deploy-artefatos"

phases:
  install:
    commands:
      - ls
      - python3 -m pip install --target . -r requirements.txt
  build:
    commands:
      - zip -r artifact.zip .
      - aws cloudformation package --template-file ./cloudformation.yml --s3-bucket $S3_ARTIFACT --output-template-file ./cloudformation.yaml
  post_build:
    commands:
      - aws s3 cp cloudformation.yaml s3://$S3_TEMPLATE/aplication-lint/templates/cloudformation.yaml
